//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektInz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Warehouse_document = new HashSet<Warehouse_document>();
            this.Warehouse_document1 = new HashSet<Warehouse_document>();
        }
    
        public int Id_company { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_adress { get; set; }
        public Nullable<int> Id_company_type { get; set; }
        public string Number { get; set; }
        public string Email_adress { get; set; }
        public string NIP { get; set; }
        public string REGON { get; set; }
        public string Contact_person { get; set; }
        public string Bank { get; set; }
        public string Account_number { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Company_Type Company_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse_document> Warehouse_document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse_document> Warehouse_document1 { get; set; }
    }
}
