//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektInz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pallet_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pallet_type()
        {
            this.Pallets = new HashSet<Pallet>();
        }
    
        public int Id_type { get; set; }
        public string Name { get; set; }
        public int Width { get; set; }
        public int Lenght { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pallet> Pallets { get; set; }
    }
}
