//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektInz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehousedbEntities : DbContext
    {
        public WarehousedbEntities()
            : base("name=WarehousedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adresses { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Company_Type> Company_Type { get; set; }
        public virtual DbSet<Dangerous_Goods> Dangerous_Goods { get; set; }
        public virtual DbSet<Document_type> Document_type { get; set; }
        public virtual DbSet<Pallet> Pallets { get; set; }
        public virtual DbSet<Pallet_type> Pallet_type { get; set; }
        public virtual DbSet<Position_title> Position_title { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<VAT_rate> VAT_rate { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<Warehouse_document> Warehouse_document { get; set; }
        public virtual DbSet<Warehouse_Operation> Warehouse_Operation { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
