//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektInz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_Operation
    {
        public int Id_operation { get; set; }
        public int Id_document { get; set; }
        public Nullable<int> Unit_weight { get; set; }
        public int Id_product { get; set; }
        public Nullable<double> Unit_net_price { get; set; }
        public int Amount_product { get; set; }
        public Nullable<int> Id_VAT { get; set; }
        public Nullable<int> Id_VAT_service { get; set; }
        public Nullable<double> Service_net_price { get; set; }
        public int Id_pallet { get; set; }
    
        public virtual Pallet Pallet { get; set; }
        public virtual Product Product { get; set; }
        public virtual VAT_rate VAT_rate { get; set; }
        public virtual VAT_rate VAT_rate1 { get; set; }
        public virtual Warehouse_document Warehouse_document { get; set; }
    }
}
