//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektInz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouse_document()
        {
            this.Warehouse_Operation = new HashSet<Warehouse_Operation>();
        }
    
        public int Id_document { get; set; }
        public string Doc_number { get; set; }
        public int Id_foreign_company { get; set; }
        public int Id_our_company { get; set; }
        public int Id_type { get; set; }
        public int Id_worker { get; set; }
        public System.DateTime Issue_date { get; set; }
        public System.DateTime Operation_date { get; set; }
        public string Comments { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Document_type Document_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse_Operation> Warehouse_Operation { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
