//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektInz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Warehouse_document = new HashSet<Warehouse_document>();
        }
    
        public int Id_worker { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_adress { get; set; }
        public Nullable<int> Id_position { get; set; }
        public string Surname { get; set; }
        public string Number { get; set; }
        public string Email_adress { get; set; }
        public string Hash { get; set; }
        public string Salt { get; set; }
        public string PESEL { get; set; }
        public System.DateTime Birth_date { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Position_title Position_title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse_document> Warehouse_document { get; set; }
    }
}
